# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TriangleArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('keywords', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('genre', models.CharField(max_length=200)),
                ('notes_1', models.TextField()),
                ('notes_2', models.TextField()),
                ('notes_3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TriangleIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('volume', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
                ('issue_url', models.TextField()),
                ('notes_1', models.TextField()),
                ('notes_2', models.TextField()),
                ('notes_3', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='trianglearticle',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browse.TriangleIssue'),
        ),
    ]
