# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 02:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trianglearticle',
            old_name='votes',
            new_name='page',
        ),
    ]
